/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.CasoClinico;
import model.CasoClinicoDao;

/**
 *
 * @author emano
 */
public class Consulta extends javax.swing.JFrame {
        private String Usuario;
        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Consulta.class.getName());

    /**
     * Creates new form Consulta
     */
    public Consulta(String nome) {
        initComponents();
        setLocationRelativeTo(null);
        this.Usuario = nome;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCasos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton2.setText("Voltar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tabelaCasos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Professor", "Titulo", "Descrição", "Pergunta"
            }
        ));
        jScrollPane1.setViewportView(tabelaCasos);

        jButton1.setText("Editar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton4.setText("Excluir");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        jButton6.setText("Inner Join");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Left join");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        jButton3.setText("Adicionar Pergunta");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 586, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2)
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton7)
                            .addComponent(jButton6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        TelaPrincipal novaTela = new TelaPrincipal(Usuario);
        novaTela.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaCasos.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um caso clínico na tabela primeiro.");
            return; 
        }
        String tituloSelecionado = tabelaCasos.getValueAt(linhaSelecionada, 1).toString();
        String descricaoAtual = tabelaCasos.getValueAt(linhaSelecionada, 2).toString();
        String novaDescricao = JOptionPane.showInputDialog(null, "Edite a descrição:", descricaoAtual);
        if (novaDescricao != null && !novaDescricao.trim().isEmpty()) {
        
        CasoClinicoDao dao = new CasoClinicoDao();
            try {
                dao.editarDescricao(tituloSelecionado, novaDescricao);
                JOptionPane.showMessageDialog(null, "Descrição atualizada!");
                listarCasosClinicos();
            } catch (SQLException ex) {
                System.getLogger(Consulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            }else{
            JOptionPane.showMessageDialog(null, "Erro ao atualizar no banco de dados.");
        }
        
        

    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
            try {
                listarLeft();
            } catch (SQLException ex) {
                System.getLogger(Consulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
            try {
                // TODO add your handling code here:
                listarCasosClinicos();
            } catch (SQLException ex) {
                System.getLogger(Consulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaCasos.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um caso clínico na tabela primeiro.");
            return; 
        }
        String tituloSelecionado = tabelaCasos.getValueAt(linhaSelecionada, 1).toString();
        String descricaoAtual = tabelaCasos.getValueAt(linhaSelecionada, 2).toString();
        CasoClinicoDao dao = new CasoClinicoDao();
            try {
                dao.excluir(tituloSelecionado, descricaoAtual);
                JOptionPane.showMessageDialog(null, "Tabela atualizada!");
                listarCasosClinicos();
            } catch (SQLException ex) {
                System.getLogger(Consulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int linhaSelecionada = tabelaCasos.getSelectedRow();
        if (linhaSelecionada == -1) {
            JOptionPane.showMessageDialog(null, "Por favor, selecione um caso clínico na tabela primeiro.");
            return; 
        }
        Object objTitulo = tabelaCasos.getValueAt(linhaSelecionada, 1);
        String tituloSelecionado = objTitulo != null ? objTitulo.toString() : "";
    
        Object objDescricao = tabelaCasos.getValueAt(linhaSelecionada, 2);
        String descricaoAtual = objDescricao != null ? objDescricao.toString() : "";
    
        Object objPergunta = tabelaCasos.getValueAt(linhaSelecionada, 3);
        String perguntaAtual = objPergunta != null ? objPergunta.toString() : "";
        String novaPergunta = JOptionPane.showInputDialog(null, "Edite a descrição:", perguntaAtual);
        if (novaPergunta != null) {
        
        CasoClinicoDao dao = new CasoClinicoDao();
            try {
                dao.perguntaAdd(tituloSelecionado, descricaoAtual,novaPergunta);
                JOptionPane.showMessageDialog(null, "Pergunta atualizada!");
                listarCasosClinicos();
            } catch (SQLException ex) {
                System.getLogger(Consulta.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }
            }else{
            JOptionPane.showMessageDialog(null, "Erro ao atualizar no banco de dados.");
        }
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void listarLeft() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) tabelaCasos.getModel();
        modelo.setNumRows(0); 

    
        CasoClinicoDao dao = new CasoClinicoDao();
        List<CasoClinico> lista = dao.listarLeft();

        for (CasoClinico c : lista){
            modelo.addRow(new Object[]{
                c.getProfessor() != null ? c.getProfessor().getNome() : "Sem Professor",
                c.getTitulo(),
                c.getDescricao(),
                c.getPergunta() != null ? c.getPergunta().getEnuciado() : "Sem pergunta"
            });
        }
    }
    
    public void listarCasosClinicos() throws SQLException{
        DefaultTableModel modelo = (DefaultTableModel) tabelaCasos.getModel();
        modelo.setNumRows(0); 

    
        CasoClinicoDao dao = new CasoClinicoDao();
        List<CasoClinico> lista = dao.listarTodos();

        for (CasoClinico c : lista){
            modelo.addRow(new Object[]{
                c.getProfessor().getNome(),
                c.getTitulo(),
                c.getDescricao(),
                c.getPergunta().getEnuciado()
            });
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Consulta("teste").setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaCasos;
    // End of variables declaration//GEN-END:variables
}
